# File: .github/workflows/workflow.yml
on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Name of Resource Group to Deploy into.'
        default: 'DSOH2'
        required: true
name: deploy-aks-secure-cli
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.28.0
        inlineScript: |
          az deployment group create -g ${{ github.event.inputs.resourceGroupName }} --template-uri https://github.com/Azure/Aks-Construction/releases/download/0.1.7-preview/main.json --parameters aks-secure-deploy.parameters.json