on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Name of Resource Group to Deploy into.'
        default: 'Skyline-Basic'
        required: true
      azAksClusterName:
        description: 'Your AKS Cluster Name'
        default: 'aks-skyline-basic'
        required: true
      azK8sNamespace:
        description: 'Name of your K8s Namespace.'
        default: 'web-app'
        required: true
      azWebAppName:
        description: 'Name of web app being deployed to AKS.'
        default: 'mvcwebapp'
        required: true
      azWebAPIName:
        description: 'Name of web api being deployed to AKS.'
        default: 'webapi'
        required: true
name: webapp-deploy-aks
env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  CLUSTER_NAME: ${{ github.event.inputs.azAksClusterName }}
  CLUSTER_RESOURCE_GROUP: ${{ github.event.inputs.resourceGroupName }}
  NAMESPACE: ${{ github.event.inputs.azK8sNamespace }}
  WEB_APP_NAME: ${{ github.event.inputs.azWebAppName }}
  WEB_API_NAME: ${{ github.event.inputs.azWebAPIName }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Set the target Azure Kubernetes Service (AKS) cluster.
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    # Create namespace if doesn't exist
    - run: |
        echo $ {{ env.REGISTRY_NAME }}
        echo $ {{ env.CLUSTER_NAME }}
        echo $ {{ env.CLUSTER_RESOURCE_GROUP }}
        echo $ {{ env.NAMESPACE }}
        echo $ {{ env.APP_NAME }}
        pwd
        ls -l

        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -

    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/mvcwebapp-aks-deploy.yaml
        images: |
          ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.WEB_APP_NAME }}:latest
          ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.WEB_API_NAME }}:latest
        namespace: ${{ env.NAMESPACE }}